### ISSUE TITLE
Resolution check is wrong, I'm running on a 4k TV

### ISSUE THREAD

**Issue by saulob** [mq1n/Win11SysCheck#1]
It says that I'm using 1280x720 

![image](https://user-images.githubusercontent.com/3660977/123529570-ff993a00-d6c7-11eb-8ef3-d866d0ea7f98.png)

My Windows 10 settings:

![image](https://user-images.githubusercontent.com/3660977/123529582-193a8180-d6c8-11eb-8f6f-2178d1a88187.png)

**Comment by TheDestinyGroup** [comment]
Saulob,

I'm not surprised the results show 1280x720 as you're using 300% desktop scaling and a lot of windows function calls don't properly handle desktop scaling so the result you get is the effective resolution which in you case is 3840/3 x 2160/3 which becomes 1280x720.

Les

**Comment by mq1n** [comment]
Can you check again with latest commit?

**Comment by saulob** [comment]
Sure.

Showing the same resolution, but passed this time :) 
Thanks.

Some questions:
- What's firmware type 2?
- And even without Secure boot enabled I passed? Maybe a better message "Secure boot capable, should be enabled to pass"?

![image](https://user-images.githubusercontent.com/3660977/123547362-dbc10d00-d736-11eb-9c80-e3d187785fc0.png)

**Comment by mq1n** [comment]
It's looks like @TheDestinyGroup mentioned scale problem, I can add a scale factor to check function but I'm not sure can it be pass then Windows's check too when Windows 11 is released. So for now I will wait until insider version is released.

Firmware type 2 is pointing to UEFI.
As current Microsoft's [system requirement documents](https://www.microsoft.com/en-us/windows/windows-11-specifications) just pointing to capability of Secure boot, there is not enabled status check currently.

**Comment by mq1n** [comment]
As far as I see current resolution checks just pointing to 720p, I changed latest minimum value(1366x768) to 1280x760 and its will support with non-scaled value too. d33d4c77fbce533f4b574255bd9f739ad5c95bc4
