### ISSUE TITLE
error 13

### ISSUE THREAD

**Issue by jukebox1001** [mq1n/Win11SysCheck#3]
I'm getting the following error:

GetPhysicallyInstalledSystemMemory failed with error: 13

Tested RAM (2 x 8 GB DDR4 2666 MHz) with memtest86+, all fine.

When I run win11syscheck again it skips all previous checks and jumps immediately to the error message, is there some log file from a previous test to be deleted?

**Comment by mq1n** [comment]
Fixed in d33d4c7.
