### ISSUE TITLE
For automated use, "please remove the "Press any key..

### ISSUE THREAD

**Issue by gpglang** [mq1n/Win11SysCheck#6]
For running this great exe file on multiple machines unattended, it would be great to be able to skip the "Press any key..".  Is that possible / easy to do?

**Comment by mq1n** [comment]
I added "-skip-wait" argument for skip waiting key handle in exit phase. f4aa78f85f9c65a1146964721fb8bfc989246b4a

**Comment by gpglang** [comment]
Cool!!  Thx!


Met vriendelijke groet, With kind regards, avec Cordialement,

***@***.***D774A6.42B1A310]

Guido Langendorff
Schepenveld 21-14
3891 ZK   Zeewolde
Netherlands
Telefoon: +31(0)85 0410099
Mobiel: +31(0)6 1945 8681
***@***.***D774A6.42B1A310]<https://www.facebook.com/automatex.zeewolde>  ***@***.***D774A6.42B1A310] <https://www.linkedin.com/company/automatex-zeewolde>   ***@***.***D774A6.42B1A310] <https://www.automatex.nl/>   ***@***.***D774A6.42B1A310] <https://www.youtube.com/channel/UCataKJKC09oDbMlUPzA5r6A>

Van: mq1n ***@***.***>
Verzonden: vrijdag 9 juli 2021 09:38
Aan: mq1n/Win11SysCheck ***@***.***>
CC: Guido Langendorff ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mq1n/Win11SysCheck] For automated use, "please remove the "Press any key.. (#6)


I added "-skip-wait" argument for skip waiting key handle in exit phase.

**Comment by gpglang** [comment]
Thx
